create table sensor(
    name varchar(100) not null unique primary key
);



create table measurements(
                             id bigint generated by default as identity primary key ,
                             value decimal,
                             raining boolean,
                             sensor_name varchar references sensor(name) on delete cascade

);

alter table measurements add column make_date date not null default current_date;

create unique index measurements_sensor_type_index on measurements(sensor_name, id);