create table usr(
                    usr_id bigint primary key generated by default as identity ,
                    email varchar unique not null ,
                    password varchar not null,
                    role varchar not null
);

create table sensor(
                       sensor_id bigint primary key generated by default as identity,
                       name varchar not null unique ,
                       owner_id bigint references usr(usr_id) on delete cascade
);

create table measurement(
                            measurement_id bigint primary key generated by default as identity ,
                            value numeric not null ,
                            raining boolean,
                            sensor_name varchar references sensor(name) on delete cascade ,
                            make_date timestamp not null default current_date
);
